# screens/metadata_screen.py
# Media Metadata Inspector + AI-generation indicator
# Shows EXIF/video metadata and flags suspicious patterns

import os, json, re, subprocess, threading, datetime

from kivy.uix.screenmanager import Screen
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.gridlayout import GridLayout
from kivy.uix.scrollview import ScrollView
from kivy.uix.button import Button
from kivy.uix.label import Label
from kivy.uix.filechooser import FileChooserIconView
from kivy.uix.popup import Popup
from kivy.uix.image import Image as KivyImage
from kivy.uix.textinput import TextInput
from kivy.uix.checkbox import CheckBox
from kivy.clock import Clock
from kivy.metrics import dp
from kivy.core.clipboard import Clipboard

try:
    from PIL import Image as PILImage
    from PIL.ExifTags import TAGS, GPSTAGS
    HAS_PIL = True
except ImportError:
    HAS_PIL = False

try:
    import cv2
    HAS_CV2 = True
except ImportError:
    HAS_CV2 = False

import app_data

IMAGE_EXTS = {".jpg",".jpeg",".png",".bmp",".gif",".webp",".tiff",".tif"}
VIDEO_EXTS = {".mp4",".mkv",".avi",".mov",".wmv",".flv",".webm",".m4v"}

# Formats Pillow can reliably write EXIF back to. TIFF deliberately left
# out here even though it can technically carry EXIF - it uses its own
# tag-writing path (tiffinfo) rather than the generic exif= kwarg, and
# getting that wrong risks silently corrupting the file, so it's not
# worth the risk without being able to verify it thoroughly.
EDITABLE_EXTS = {".jpg", ".jpeg", ".png", ".webp"}

# tag name -> numeric EXIF tag id, for the fields we let you edit.
# Make/Model/Software/Artist/Copyright/DateTime live on the main IFD.
# DateTimeOriginal lives in the Exif sub-IFD (0x8769) instead - handled
# separately since it needs get_ifd(), and older Pillow versions can be
# unreliable writing to it, so that one field degrades gracefully.
EDITABLE_TAGS = {
    "Make": 271, "Model": 272, "Software": 305,
    "Artist": 315, "Copyright": 33432, "DateTime": 306,
}
EXIF_IFD_TAG = 0x8769          # sub-IFD holding DateTimeOriginal etc.
DATETIME_ORIGINAL_TAG = 36867
GPS_IFD_TAG = 0x8825

# ── AI indicator rules ────────────────────────────────────────────────────────
# Each rule: (field, pattern, flag_level, reason)
# flag_level: "green"=clean, "yellow"=suspicious, "red"=red flag
AI_RULES = [
    # Software signatures
    ("Software", r"(?i)stable.diffusion|midjourney|dall.?e|imagen|"
                 r"firefly|leonardo|runway|kling|sora|pika|gen-2|"
                 r"civitai|automatic1111|comfyui|invokeai|diffusers",
     "red", "Known AI generation software detected in metadata"),
    ("Software", r"(?i)adobe.photoshop|lightroom|gimp|affinity",
     "green", "Known photo editor (not AI-specific)"),
    ("ProcessingSoftware", r"(?i)stable.diffusion|midjourney|dall.?e",
     "red", "AI processing software in metadata"),
    # Missing camera info
    ("Make", r"^$", "yellow", "No camera make recorded"),
    ("Model", r"^$", "yellow", "No camera model recorded"),
    # Suspicious creation tools
    ("Creator", r"(?i)ai|bot|generated|synthetic|fake",
     "red", "Creator field suggests AI generation"),
    ("Description", r"(?i)generated by|created by ai|prompt:|negative prompt:",
     "red", "Description contains AI generation language"),
    ("Comment", r"(?i)prompt:|steps:|cfg.?scale:|sampler:|seed:",
     "red", "Comment contains AI generation parameters"),
    # PNG specific (SD often writes here)
    ("parameters", r"(?i)steps:|cfg|sampler|seed|negative",
     "red", "PNG parameters chunk contains Stable Diffusion settings"),
    # Dates
    ("DateTimeOriginal", r"^$", "yellow", "No original capture date"),
    # GPS
    ("GPSInfo", r"^$", "yellow", "No GPS data (not conclusive alone)"),
]

# Known clean camera makes
CAMERA_MAKES = {"canon","nikon","sony","fujifilm","olympus","panasonic",
                "leica","hasselblad","pentax","ricoh","apple","samsung",
                "google","huawei","xiaomi","oppo","motorola","lg"}

def _extract_image_meta(path):
    """Returns dict of metadata fields from image."""
    meta = {}
    if not HAS_PIL:
        return meta
    try:
        img = PILImage.open(path)
        meta["Format"]    = img.format or "Unknown"
        meta["Mode"]      = img.mode
        meta["Size"]      = f"{img.width} x {img.height} px"
        meta["File size"] = _fmt_size(os.path.getsize(path))

        # EXIF
        exif_raw = img._getexif() if hasattr(img, "_getexif") else None
        if exif_raw:
            for tag_id, val in exif_raw.items():
                tag = TAGS.get(tag_id, str(tag_id))
                if isinstance(val, bytes):
                    try: val = val.decode("utf-8", errors="replace")
                    except: val = repr(val)
                meta[tag] = str(val)[:300]
        else:
            meta["EXIF"] = "None found"

        # PNG text chunks (Stable Diffusion stores prompts here)
        if hasattr(img, "text") and img.text:
            for k, v in img.text.items():
                meta[f"PNG:{k}"] = str(v)[:500]

        # XMP
        if hasattr(img, "info"):
            for k, v in img.info.items():
                if k not in ("exif",) and isinstance(v, (str, int, float)):
                    meta[f"Info:{k}"] = str(v)[:200]
    except Exception as e:
        meta["Error"] = str(e)
    return meta

def _extract_video_meta(path):
    """Returns dict of metadata from video using cv2 + ffprobe if available."""
    meta = {}
    meta["File size"] = _fmt_size(os.path.getsize(path))
    meta["Format"]    = os.path.splitext(path)[1].upper().lstrip(".")

    if HAS_CV2:
        try:
            cap = cv2.VideoCapture(path)
            fps   = cap.get(cv2.CAP_PROP_FPS)
            total = cap.get(cv2.CAP_PROP_FRAME_COUNT)
            w     = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            h     = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            cap.release()
            dur = total / fps if fps else 0
            meta["Resolution"] = f"{w} x {h} px"
            meta["Duration"]   = _fmt_dur(dur)
            meta["FPS"]        = f"{fps:.2f}"
            meta["Frames"]     = str(int(total))
        except Exception as e:
            meta["cv2 error"] = str(e)

    # ffprobe for rich metadata
    try:
        result = subprocess.run(
            ["ffprobe", "-v", "quiet", "-print_format", "json",
             "-show_format", "-show_streams", path],
            capture_output=True, text=True, timeout=8)
        if result.returncode == 0:
            data = json.loads(result.stdout)
            fmt  = data.get("format", {})
            tags = fmt.get("tags", {})
            for k, v in tags.items():
                meta[f"Tag:{k}"] = str(v)[:300]
            meta["Bit rate"] = fmt.get("bit_rate", "?")
            # streams
            for i, stream in enumerate(data.get("streams", [])):
                t = stream.get("codec_type","?")
                c = stream.get("codec_name","?")
                meta[f"Stream {i} ({t})"] = c
                st = stream.get("tags", {})
                for k, v in st.items():
                    meta[f"Stream{i}:{k}"] = str(v)[:200]
    except FileNotFoundError:
        meta["ffprobe"] = "Not installed (apt install ffmpeg)"
    except Exception as e:
        meta["ffprobe error"] = str(e)

    return meta

def _video_thumb(path):
    """Grab a single frame from a video so it can be previewed too."""
    if not (HAS_CV2 and HAS_PIL):
        return None
    try:
        cache = app_data.subdir("metadata_cache")
        name  = f"mt_{abs(hash(path))}.jpg"
        thumb = os.path.join(cache, name)
        if os.path.exists(thumb):
            return thumb
        cap   = cv2.VideoCapture(path)
        total = cap.get(cv2.CAP_PROP_FRAME_COUNT)
        cap.set(cv2.CAP_PROP_POS_FRAMES, max(0, int(total * 0.05)))
        ok, frame = cap.read()
        cap.release()
        if ok:
            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            PILImage.fromarray(rgb).save(thumb, "JPEG", quality=82)
            return thumb
    except Exception:
        pass
    return None


def _analyse_ai(meta):
    """
    Returns list of (level, reason) tuples.
    Levels: "green", "yellow", "red"
    """
    findings = []
    make = meta.get("Make", "").lower()

    # Check camera make first
    if make:
        if any(m in make for m in CAMERA_MAKES):
            findings.append(("green",
                f"Camera make recognised: {meta['Make']}"))
        else:
            findings.append(("yellow",
                f"Unknown camera make: {meta['Make']}"))
    else:
        findings.append(("yellow", "No camera make (could be screenshot/AI)"))

    # Run all rules
    for field, pattern, level, reason in AI_RULES:
        val = None
        fl = field.lower()
        # exact key match first, so e.g. field "Model" doesn't accidentally
        # pick up the value of an unrelated "LensModel" tag
        for k, v in meta.items():
            if k.lower() == fl:
                val = str(v)
                break
        if val is None:
            # fall back to substring match, needed for prefixed keys like
            # "PNG:parameters" or "Stream0:codec"
            for k, v in meta.items():
                if fl in k.lower():
                    val = str(v)
                    break
        val = val or ""
        if pattern == r"^$":
            if not val:
                findings.append((level, reason))
        else:
            if re.search(pattern, val):
                findings.append((level, reason))

    # Video-specific: no tags at all = suspicious
    if not any(k.startswith("Tag:") for k in meta):
        if meta.get("Format","") in ("MP4","MKV","WEBM","MOV"):
            findings.append(("yellow",
                "No metadata tags in video container"))

    # PNG with no EXIF but has PNG text = very suspicious (SD pattern)
    if any(k.startswith("PNG:") for k in meta):
        findings.append(("red",
            "PNG text chunks present — common in AI-generated images"))

    return findings

def _verdict(findings):
    levels = [f[0] for f in findings]
    reds    = levels.count("red")
    yellows = levels.count("yellow")
    greens  = levels.count("green")
    if reds >= 2:
        return "red", "HIGH RISK — likely AI generated"
    elif reds == 1:
        return "red", "RED FLAG — strong AI indicator found"
    elif yellows >= 3:
        return "yellow", "SUSPICIOUS — multiple weak indicators"
    elif yellows >= 1 and greens == 0:
        return "yellow", "SUSPICIOUS — missing expected camera data"
    elif greens >= 1 and reds == 0 and yellows <= 1:
        return "green", "LIKELY REAL — camera metadata present"
    else:
        return "yellow", "UNCERTAIN — mixed signals"

def _fmt_size(b):
    if b < 1024: return f"{b} B"
    elif b < 1048576: return f"{b/1024:.1f} KB"
    elif b < 1073741824: return f"{b/1048576:.1f} MB"
    return f"{b/1073741824:.2f} GB"

def _fmt_dur(s):
    s = int(s); h = s//3600; m=(s%3600)//60; sc=s%60
    return f"{h}:{m:02d}:{sc:02d}" if h else f"{m}:{sc:02d}"

LEVEL_COLORS = {
    "red":    (1.0, 0.3, 0.3, 1),
    "yellow": (1.0, 0.85, 0.2, 1),
    "green":  (0.3, 0.9, 0.4, 1),
}


class MetadataScreen(Screen):
    def __init__(self, **kw):
        super().__init__(**kw)
        self._meta     = {}
        self._findings = []
        self._path     = None

        root = BoxLayout(orientation="vertical", padding=6, spacing=5)

        root.add_widget(Label(
            text="Media Metadata Inspector",
            size_hint_y=None, height=dp(30), font_size=17, bold=True))

        # ── pick file ──────────────────────────────────────────────────────
        pick_row = BoxLayout(size_hint_y=None, height=dp(42), spacing=6)
        pick_btn = Button(text="Open Image / Video", font_size=14)
        pick_btn.bind(on_release=self._pick_file)
        self._file_lbl = Label(text="No file selected", font_size=11,
                               halign="left", color=(0.6, 0.8, 1, 1))
        self._file_lbl.bind(size=self._file_lbl.setter("text_size"))
        pick_row.add_widget(pick_btn)
        pick_row.add_widget(self._file_lbl)
        root.add_widget(pick_row)

        # ── preview ────────────────────────────────────────────────────────
        self._preview_img = KivyImage(
            size_hint_y=0.20, fit_mode="contain")
        root.add_widget(self._preview_img)

        # ── verdict banner ─────────────────────────────────────────────────
        self._verdict_lbl = Label(
            text="", size_hint_y=None, height=dp(36),
            font_size=16, bold=True, halign="center")
        self._verdict_lbl.bind(size=self._verdict_lbl.setter("text_size"))
        root.add_widget(self._verdict_lbl)

        # ── findings ───────────────────────────────────────────────────────
        root.add_widget(Label(text="AI Indicators:", size_hint_y=None,
                              height=dp(20), font_size=13, bold=True))
        sv_find = ScrollView(size_hint=(1, 0.22))
        self._find_grid = GridLayout(cols=1, spacing=2, size_hint_y=None)
        self._find_grid.bind(minimum_height=self._find_grid.setter("height"))
        sv_find.add_widget(self._find_grid)
        root.add_widget(sv_find)

        # ── raw metadata ───────────────────────────────────────────────────
        meta_hdr = BoxLayout(size_hint_y=None, height=dp(26), spacing=6)
        meta_hdr.add_widget(Label(text="Raw Metadata:", font_size=13,
                                  bold=True))
        copy_btn = Button(text="Copy all", size_hint_x=None, width=dp(82),
                          font_size=12)
        copy_btn.bind(on_release=self._copy_meta)
        meta_hdr.add_widget(copy_btn)
        export_btn = Button(text="Export JSON", size_hint_x=None, width=dp(94),
                            font_size=12)
        export_btn.bind(on_release=self._export_json)
        meta_hdr.add_widget(export_btn)
        self._edit_btn = Button(text="Edit Metadata...", size_hint_x=None,
                                width=dp(116), font_size=12, disabled=True)
        self._edit_btn.bind(on_release=self._open_edit_popup)
        meta_hdr.add_widget(self._edit_btn)
        root.add_widget(meta_hdr)

        sv_meta = ScrollView(size_hint=(1, 0.42))
        self._meta_grid = GridLayout(cols=2, spacing=2, size_hint_y=None,
                                     padding=4)
        self._meta_grid.bind(minimum_height=self._meta_grid.setter("height"))
        sv_meta.add_widget(self._meta_grid)
        root.add_widget(sv_meta)

        back = Button(text="Back", size_hint_y=None, height=dp(42))
        back.bind(on_release=lambda *a: setattr(
            self.manager, "current", "dashboard"))
        root.add_widget(back)

        self.add_widget(root)

    # ── file picker ───────────────────────────────────────────────────────
    def _pick_file(self, *a):
        chooser = FileChooserIconView(
            path=os.path.expanduser("~"), multiselect=False)
        btn = Button(text="Inspect this file", size_hint_y=None, height=dp(44))
        layout = BoxLayout(orientation="vertical")
        layout.add_widget(chooser); layout.add_widget(btn)
        popup = Popup(title="Select image or video", content=layout,
                      size_hint=(0.92, 0.92))

        def _sel(*a):
            if chooser.selection:
                path = chooser.selection[0]
                popup.dismiss()
                self._analyse(path)
            else:
                popup.dismiss()

        btn.bind(on_release=_sel)
        popup.open()

    # ── analysis ──────────────────────────────────────────────────────────
    def _analyse(self, path):
        self._path = path
        name = os.path.basename(path)
        self._file_lbl.text = name
        self._verdict_lbl.text = "Analysing..."
        self._verdict_lbl.color = (0.7, 0.7, 0.7, 1)
        self._find_grid.clear_widgets()
        self._meta_grid.clear_widgets()

        ext = os.path.splitext(path)[1].lower()
        self._edit_btn.disabled = not (HAS_PIL and ext in EDITABLE_EXTS)
        if ext in IMAGE_EXTS:
            # images can be shown straight away, no extraction needed
            self._preview_img.source = path
            self._preview_img.reload()
        else:
            self._preview_img.source = ""

        def _run():
            if ext in IMAGE_EXTS:
                meta = _extract_image_meta(path)
                thumb = None
            elif ext in VIDEO_EXTS:
                meta = _extract_video_meta(path)
                thumb = _video_thumb(path)
            else:
                meta = {"Error": "Unsupported file type"}
                thumb = None

            findings = _analyse_ai(meta)
            level, verdict_text = _verdict(findings)

            def _apply(dt):
                if self._path != path:
                    return  # a different file was picked while this ran
                self._meta     = meta
                self._findings = findings
                if thumb and os.path.exists(thumb):
                    self._preview_img.source = thumb
                    self._preview_img.reload()
                self._show_results(meta, findings, level, verdict_text)

            Clock.schedule_once(_apply, 0)

        threading.Thread(target=_run, daemon=True).start()

    def _show_results(self, meta, findings, level, verdict_text):
        # verdict
        self._verdict_lbl.text  = verdict_text
        self._verdict_lbl.color = LEVEL_COLORS.get(level, (1,1,1,1))

        # findings
        self._find_grid.clear_widgets()
        for flevel, reason in findings:
            tag = {"red":"[RED]","yellow":"[?]","green":"[OK]"}.get(flevel,"")
            lbl = Label(
                text=f"{tag}  {reason}",
                size_hint_y=None, height=dp(22),
                font_size=11, halign="left",
                color=LEVEL_COLORS.get(flevel, (1,1,1,1)))
            lbl.bind(size=lbl.setter("text_size"))
            self._find_grid.add_widget(lbl)

        if not findings:
            self._find_grid.add_widget(Label(
                text="No indicators found.", size_hint_y=None, height=dp(22),
                font_size=11))

        # metadata table
        self._meta_grid.clear_widgets()
        for k, v in sorted(meta.items()):
            key_lbl = Label(
                text=k, size_hint_y=None, height=dp(22),
                font_size=11, bold=True, halign="left",
                color=(0.7, 0.85, 1, 1))
            key_lbl.bind(size=key_lbl.setter("text_size"))
            val_lbl = Label(
                text=str(v), size_hint_y=None,
                font_size=11, halign="left", valign="top")
            val_lbl.bind(
                width=lambda inst, w: setattr(inst, "text_size", (w, None)))
            val_lbl.bind(
                texture_size=lambda inst, ts: setattr(
                    inst, "height", max(dp(22), ts[1])))
            self._meta_grid.add_widget(key_lbl)
            self._meta_grid.add_widget(val_lbl)

    # ── export ────────────────────────────────────────────────────────────
    def _copy_meta(self, *a):
        if not self._meta:
            return
        text = "\n".join(f"{k}: {v}" for k, v in sorted(self._meta.items()))
        Clipboard.copy(text)

    def _export_json(self, *a):
        if not self._meta or not self._path:
            return
        base, _ext = os.path.splitext(self._path)
        out_path = base + "_metadata.json"
        data = {
            "file":     self._path,
            "metadata": self._meta,
            "findings": [{"level": f[0], "reason": f[1]}
                         for f in self._findings],
        }
        try:
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
            Popup(title="Exported",
                  content=Label(text=f"Saved:\n{out_path}"),
                  size_hint=(0.75, 0.35)).open()
        except Exception as e:
            Popup(title="Error", content=Label(text=str(e)),
                  size_hint=(0.65, 0.3)).open()

    # ── editing ──────────────────────────────────────────────────────────
    def _open_edit_popup(self, *a):
        if not self._path or self._edit_btn.disabled:
            return

        layout = BoxLayout(orientation="vertical", padding=8, spacing=6)
        layout.add_widget(Label(
            text="Editing only writes back the fields below - values are "
                 "read from the file's current EXIF where present.",
            font_size=10, size_hint_y=None, height=dp(30),
            halign="left", color=(0.6, 0.6, 0.6, 1)))

        inputs = {}
        for label in ("Make", "Model", "Software", "Artist", "Copyright",
                     "DateTime", "DateTimeOriginal"):
            row = BoxLayout(size_hint_y=None, height=dp(34), spacing=6)
            row.add_widget(Label(text=label, size_hint_x=None, width=dp(120),
                                 font_size=12, halign="left"))
            current = self._meta.get(label, "")
            ti = TextInput(text=current, multiline=False, font_size=12)
            inputs[label] = ti
            row.add_widget(ti)
            layout.add_widget(row)

        gps_row = BoxLayout(size_hint_y=None, height=dp(34), spacing=6)
        strip_gps_cb = CheckBox(
            active=("GPSInfo" in self._meta), size_hint=(None, None),
            size=(dp(24), dp(24)))
        gps_row.add_widget(strip_gps_cb)
        gps_row.add_widget(Label(text="Strip GPS data", font_size=12,
                                 halign="left"))
        layout.add_widget(gps_row)

        status = Label(text="", size_hint_y=None, height=dp(22), font_size=11,
                      color=(0.6, 0.8, 1, 1))
        layout.add_widget(status)

        btn_row = BoxLayout(size_hint_y=None, height=dp(44), spacing=6)
        save_btn = Button(text="Save Changes")
        strip_btn = Button(text="Strip ALL metadata",
                           background_color=(0.5, 0.2, 0.2, 1))
        cancel_btn = Button(text="Cancel")
        btn_row.add_widget(save_btn)
        btn_row.add_widget(strip_btn)
        btn_row.add_widget(cancel_btn)
        layout.add_widget(btn_row)

        popup = Popup(title=f"Edit Metadata - {os.path.basename(self._path)}",
                      content=layout, size_hint=(0.85, 0.85))
        cancel_btn.bind(on_release=lambda *a: popup.dismiss())

        def _do_save(*a):
            values = {k: ti.text.strip() for k, ti in inputs.items()}
            save_btn.disabled = True
            status.text = "Saving..."
            self._save_metadata_edits(
                self._path, values, strip_gps_cb.active,
                lambda ok, err: self._on_edit_saved(popup, status, ok, err))

        def _do_strip_all(*a):
            self._confirm_strip_all(popup)

        save_btn.bind(on_release=_do_save)
        strip_btn.bind(on_release=_do_strip_all)
        popup.open()

    def _confirm_strip_all(self, edit_popup):
        layout = BoxLayout(orientation="vertical", padding=10, spacing=10)
        layout.add_widget(Label(
            text="This permanently removes ALL metadata (EXIF, ICC "
                 "profile, everything) from this file. There is no undo.",
            halign="center"))
        row = BoxLayout(size_hint_y=None, height=dp(44), spacing=6)
        yes = Button(text="Strip everything", background_color=(0.5,0.2,0.2,1))
        no = Button(text="Cancel")
        row.add_widget(yes)
        row.add_widget(no)
        layout.add_widget(row)
        confirm = Popup(title="Are you sure?", content=layout,
                        size_hint=(0.7, 0.4))
        no.bind(on_release=lambda *a: confirm.dismiss())

        def _yes(*a):
            confirm.dismiss()
            self._strip_all_metadata(
                self._path,
                lambda ok, err: self._on_edit_saved(edit_popup, None, ok, err))

        yes.bind(on_release=_yes)
        confirm.open()

    def _save_metadata_edits(self, path, values, strip_gps, callback):
        def worker():
            try:
                img = PILImage.open(path)
                exif = img.getexif()

                for name, tag_id in EDITABLE_TAGS.items():
                    val = values.get(name, "")
                    if val:
                        exif[tag_id] = val
                    elif tag_id in exif:
                        del exif[tag_id]

                # DateTimeOriginal lives in the Exif sub-IFD - best effort,
                # skip quietly if this Pillow version won't round-trip it
                dto = values.get("DateTimeOriginal", "")
                try:
                    sub_ifd = exif.get_ifd(EXIF_IFD_TAG)
                    if dto:
                        sub_ifd[DATETIME_ORIGINAL_TAG] = dto
                    elif DATETIME_ORIGINAL_TAG in sub_ifd:
                        del sub_ifd[DATETIME_ORIGINAL_TAG]
                except Exception:
                    pass

                if strip_gps and GPS_IFD_TAG in exif:
                    del exif[GPS_IFD_TAG]

                img.save(path, exif=exif)
                Clock.schedule_once(lambda dt: callback(True, None))
            except Exception as e:
                Clock.schedule_once(lambda dt: callback(False, str(e)))

        threading.Thread(target=worker, daemon=True).start()

    def _strip_all_metadata(self, path, callback):
        def worker():
            try:
                img = PILImage.open(path)
                img.load()
                # Rebuilding the image from raw pixel bytes (rather than
                # re-saving the original) drops EXIF, ICC profile, XMP -
                # everything, not just the fields this screen knows about.
                clean = PILImage.frombytes(img.mode, img.size, img.tobytes())
                clean.save(path)
                Clock.schedule_once(lambda dt: callback(True, None))
            except Exception as e:
                Clock.schedule_once(lambda dt: callback(False, str(e)))

        threading.Thread(target=worker, daemon=True).start()

    def _on_edit_saved(self, popup, status_lbl, ok, err):
        if ok:
            if status_lbl:
                status_lbl.text = "Saved."
            popup.dismiss()
            Popup(title="Saved", content=Label(text="Metadata updated."),
                  size_hint=(0.6, 0.3)).open()
            if self._path:
                self._analyse(self._path)   # refresh the displayed metadata
        else:
            if status_lbl:
                status_lbl.text = f"Failed: {err}"
            else:
                Popup(title="Error", content=Label(text=str(err)),
                      size_hint=(0.7, 0.35)).open()
